insert into rule_version (
    rule_code,
    version,
    parameter_json,
    score_weight,
    enabled,
    effective_from,
    effective_to,
    created_at,
    created_by,
    change_note
) values
    (
        'HIGH_RISK_IP_LOGIN',
        1,
        '{"minHighRiskIpLoginCount24h":1}',
        35,
        true,
        current_timestamp,
        null,
        current_timestamp,
        'system-init',
        'Initial login rule threshold'
    ),
    (
        'LOGIN_FAILURE_BURST',
        1,
        '{"minLoginFailureCount24h":20,"minLoginFailureRate24h":0.8}',
        40,
        true,
        current_timestamp,
        null,
        current_timestamp,
        'system-init',
        'Initial login burst rule thresholds'
    ),
    (
        'RAPID_WITHDRAW_AFTER_DEPOSIT',
        1,
        '{"maxDelayMinutes":30,"minDepositCount24h":1,"minWithdrawCount24h":1}',
        45,
        true,
        current_timestamp,
        null,
        current_timestamp,
        'system-init',
        'Initial rapid withdraw rule thresholds'
    ),
    (
        'REWARD_WITHDRAW_ABUSE',
        1,
        '{"minRewardTransactionCount30d":1,"maxRewardWithdrawDelayHours30d":24.0}',
        30,
        true,
        current_timestamp,
        null,
        current_timestamp,
        'system-init',
        'Initial reward abuse rule thresholds'
    ),
    (
        'SHARED_DEVICE_CLUSTER',
        1,
        '{"minSharedDeviceAccounts7d":5}',
        25,
        true,
        current_timestamp,
        null,
        current_timestamp,
        'system-init',
        'Initial shared device rule thresholds'
    ),
    (
        'DEVICE_SWITCH_SPIKE',
        1,
        '{"minDeviceSwitchCount24h":3,"minUniqueDeviceCount7d":2}',
        25,
        true,
        current_timestamp,
        null,
        current_timestamp,
        'system-init',
        'Initial device switch rule thresholds'
    ),
    (
        'RAPID_PROFILE_CHANGE',
        1,
        '{"requireRapidProfileChangeFlag":true}',
        20,
        true,
        current_timestamp,
        null,
        current_timestamp,
        'system-init',
        'Initial rapid profile change rule thresholds'
    ),
    (
        'SECURITY_CHANGE_BEFORE_WITHDRAW',
        1,
        '{"requireSecurityChangeBeforeWithdrawFlag":true}',
        40,
        true,
        current_timestamp,
        null,
        current_timestamp,
        'system-init',
        'Initial security change before withdraw rule thresholds'
    ),
    (
        'HIGH_RISK_NEIGHBOR_CLUSTER',
        1,
        '{"minRiskNeighborCount30d":3,"minGraphClusterSize30d":5}',
        35,
        true,
        current_timestamp,
        null,
        current_timestamp,
        'system-init',
        'Initial graph rule thresholds'
    ),
    (
        'ATO_SUSPICION_COMPOSITE',
        1,
        '{"minNewDeviceLoginCount7d":1,"minHighRiskIpLoginCount24h":1,"requireSecurityChangeBeforeWithdrawFlag":true}',
        60,
        true,
        current_timestamp,
        null,
        current_timestamp,
        'system-init',
        'Initial composite ATO rule thresholds'
    )
on conflict (rule_code, version) do update
set parameter_json = excluded.parameter_json,
    score_weight = excluded.score_weight,
    enabled = excluded.enabled,
    effective_from = excluded.effective_from,
    effective_to = excluded.effective_to,
    created_by = excluded.created_by,
    change_note = excluded.change_note;
